// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Exercise struct {
	Fitness              int32    `protobuf:"varint,1,opt,name=fitness,proto3" json:"fitness,omitempty"`
	Pilates              int32    `protobuf:"varint,2,opt,name=Pilates,proto3" json:"Pilates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exercise) Reset()         { *m = Exercise{} }
func (m *Exercise) String() string { return proto.CompactTextString(m) }
func (*Exercise) ProtoMessage()    {}
func (*Exercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Exercise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exercise.Unmarshal(m, b)
}
func (m *Exercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exercise.Marshal(b, m, deterministic)
}
func (m *Exercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exercise.Merge(m, src)
}
func (m *Exercise) XXX_Size() int {
	return xxx_messageInfo_Exercise.Size(m)
}
func (m *Exercise) XXX_DiscardUnknown() {
	xxx_messageInfo_Exercise.DiscardUnknown(m)
}

var xxx_messageInfo_Exercise proto.InternalMessageInfo

func (m *Exercise) GetFitness() int32 {
	if m != nil {
		return m.Fitness
	}
	return 0
}

func (m *Exercise) GetPilates() int32 {
	if m != nil {
		return m.Pilates
	}
	return 0
}

type Person struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32     `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Exercise             *Exercise `protobuf:"bytes,3,opt,name=Exercise,proto3" json:"Exercise,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetExercise() *Exercise {
	if m != nil {
		return m.Exercise
	}
	return nil
}

func init() {
	proto.RegisterType((*Exercise)(nil), "main.Exercise")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() {
	proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d)
}

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2,
	0xe3, 0xe2, 0x70, 0xad, 0x48, 0x2d, 0x4a, 0xce, 0x2c, 0x4e, 0x15, 0x92, 0xe0, 0x62, 0x4f, 0xcb,
	0x2c, 0xc9, 0x4b, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x41, 0x32,
	0x01, 0x99, 0x39, 0x89, 0x25, 0xa9, 0xc5, 0x12, 0x4c, 0x10, 0x19, 0x28, 0x57, 0x29, 0x8a, 0x8b,
	0x2d, 0x00, 0x6c, 0xaa, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0x2a, 0x58, 0x2b, 0x67, 0x10,
	0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x9e, 0x0a, 0xd5, 0x03, 0x62, 0x0a, 0x69, 0x21, 0xec,
	0x93, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd3, 0x03, 0x39, 0x44, 0x0f, 0x26, 0x1a, 0x04,
	0x97, 0x4f, 0x62, 0x03, 0x3b, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xd4, 0x90, 0x1b,
	0xb8, 0x00, 0x00, 0x00,
}
